name: immich-distribution-imagemagick
base: core20
version: 7.1.1-13-dist1
summary: ImageMagick packaged for Immich Distribution
description: |
  ImageMagick packaged for Immich Distribution, this is not intended to be consumed directly.
architectures:
  - amd64

grade: stable
confinement: strict

parts:
  imagemagick:
    plugin: make
    source: https://github.com/ImageMagick/ImageMagick/archive/7.1.1-13.tar.gz
    source-checksum: "sha256/8e3ce1aaad19da9f2ca444072bcc631d193a219e3ee11c13ad6d3c895044142c"
    override-build: |
      ./configure --with-modules
      snapcraftctl build
    build-packages:
      - libltdl-dev
    after:
      - cgif
    stage-packages:
      - libcairo2
      - libdatrie1
      - libde265-0
      - libdjvulibre21
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgomp1
      - libgraphite2-3
      - libharfbuzz0b
      - libheif1
      - libicu66
      - libilmbase24
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - liblqr-1-0
      - libltdl7
      - libnuma1
      - libopenexr24
      - libopenjp2-7
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libtiff5
      - libwebp6
      - libwebpdemux2
      - libwebpmux3
      - libwmf0.2-7
      - libx11-6
      - libx265-179
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxml2
      - libxrender1
    organize:
      usr/local: usr
    stage:
      - -usr/share/apport
      - -usr/share/djvu
      - -usr/share/docs
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/X11

  cgif:
    plugin: meson
    meson-version: "1.2.1"
    source: https://github.com/dloebl/cgif.git
    source-tag: "V0.3.2"
    organize:
      usr/local: usr
